# Generated by Django 3.2.3 on 2021-05-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0002_alter_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
