# Generated by Django 3.2.3 on 2021-05-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0003_auto_20210524_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='none', max_length=65),
        ),
    ]
