# Generated by Django 3.2.3 on 2021-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0005_alter_login_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='item_title',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.CharField(default='---', max_length=4),
        ),
    ]
