# Generated by Django 3.2.3 on 2021-05-27 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0006_auto_20210526_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_description',
            new_name='item_caption',
        ),
    ]
