# Generated by Django 3.2.3 on 2021-05-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0007_rename_item_description_item_item_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='none', upload_to='items'),
        ),
    ]
