# Generated by Django 3.2.3 on 2021-05-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0008_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(upload_to='items'),
        ),
    ]
