# Generated by Django 3.2.3 on 2021-06-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0009_alter_item_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('delivery_longtitude', models.FloatField(default=0)),
                ('delivery_latitude', models.FloatField(default=0)),
            ],
        ),
    ]
