# Generated by Django 3.2.3 on 2021-06-02 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0010_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='item',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.item'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.user'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_count',
            field=models.CharField(default='calculate the count', max_length=20),
        ),
    ]
