# Generated by Django 3.2.3 on 2021-06-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0011_auto_20210602_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.user', to_field='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
