# Generated by Django 3.2.3 on 2021-06-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0012_auto_20210604_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.user', to_field='email'),
        ),
    ]
