# Generated by Django 3.2.3 on 2021-06-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0013_alter_login_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.user', to_field='email'),
        ),
    ]
