# Generated by Django 3.2.3 on 2021-06-07 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0014_alter_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverer_active', models.BooleanField(default=False)),
                ('deliverer_lat', models.FloatField(default=0)),
                ('deliverer_long', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_route', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_longtitude', models.FloatField(default=0)),
                ('delivery_latitude', models.FloatField(default=0)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.item')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='isDeliverer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.user'),
        ),
        migrations.AddField(
            model_name='deliverer',
            name='Delivery_details_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.deliverydetails'),
        ),
        migrations.AddField(
            model_name='deliverer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.user'),
        ),
    ]
