# Generated by Django 3.2.3 on 2021-06-15 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0015_auto_20210607_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverer',
            name='Delivery_details_id',
        ),
        migrations.RemoveField(
            model_name='deliverer',
            name='id',
        ),
        migrations.AddField(
            model_name='deliverer',
            name='delivery_details_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kickons_inventory.deliverydetails'),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.user'),
        ),
    ]
