# Generated by Django 3.2.3 on 2021-06-18 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0016_auto_20210615_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverer',
            name='delivery_details_id',
        ),
        migrations.AddField(
            model_name='deliverer',
            name='DeliveryDetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.deliverydetails'),
        ),
        migrations.AddField(
            model_name='deliverer',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.user'),
        ),
    ]
