# Generated by Django 3.2.3 on 2021-06-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0017_auto_20210618_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverer',
            name='DeliveryDetails',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.deliverydetails'),
        ),
    ]
