# Generated by Django 3.2.3 on 2021-06-27 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0021_alter_deliverer_deliverydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverer',
            name='id',
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kickons_inventory.user'),
        ),
    ]
