# Generated by Django 3.2.3 on 2021-06-27 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kickons_inventory', '0023_alter_deliverer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverer',
            name='DeliveryDetails',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kickons_inventory.deliverydetails', unique=True),
        ),
    ]
